/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppRulesRouteImport } from './routes/app/rules'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppRulesNewRouteImport } from './routes/app/rules.new'
import { Route as AppRulesIdRouteImport } from './routes/app/rules.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesNewRoute = AppRulesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRulesRoute,
} as any)
const AppRulesIdRoute = AppRulesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRulesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/rules': typeof AppRulesRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/rules/$id': typeof AppRulesIdRoute
  '/app/rules/new': typeof AppRulesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/rules': typeof AppRulesRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/rules/$id': typeof AppRulesIdRoute
  '/app/rules/new': typeof AppRulesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/rules': typeof AppRulesRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/rules/$id': typeof AppRulesIdRoute
  '/app/rules/new': typeof AppRulesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/documents'
    | '/app/rules'
    | '/app/'
    | '/app/rules/$id'
    | '/app/rules/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/documents'
    | '/app/rules'
    | '/app'
    | '/app/rules/$id'
    | '/app/rules/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/documents'
    | '/app/rules'
    | '/app/'
    | '/app/rules/$id'
    | '/app/rules/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rules': {
      id: '/app/rules'
      path: '/rules'
      fullPath: '/app/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rules/new': {
      id: '/app/rules/new'
      path: '/new'
      fullPath: '/app/rules/new'
      preLoaderRoute: typeof AppRulesNewRouteImport
      parentRoute: typeof AppRulesRoute
    }
    '/app/rules/$id': {
      id: '/app/rules/$id'
      path: '/$id'
      fullPath: '/app/rules/$id'
      preLoaderRoute: typeof AppRulesIdRouteImport
      parentRoute: typeof AppRulesRoute
    }
  }
}

interface AppRulesRouteChildren {
  AppRulesIdRoute: typeof AppRulesIdRoute
  AppRulesNewRoute: typeof AppRulesNewRoute
}

const AppRulesRouteChildren: AppRulesRouteChildren = {
  AppRulesIdRoute: AppRulesIdRoute,
  AppRulesNewRoute: AppRulesNewRoute,
}

const AppRulesRouteWithChildren = AppRulesRoute._addFileChildren(
  AppRulesRouteChildren,
)

interface AppRouteChildren {
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppRulesRoute: typeof AppRulesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDocumentsRoute: AppDocumentsRoute,
  AppRulesRoute: AppRulesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
