/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppRulesRouteImport } from './routes/app/rules'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppAlertsRouteImport } from './routes/app/alerts'
import { Route as AppAlertsIndexRouteImport } from './routes/app/alerts.index'
import { Route as AppRulesNewRouteImport } from './routes/app/rules.new'
import { Route as AppRulesIdRouteImport } from './routes/app/rules.$id'
import { Route as AppAlertsIdRouteImport } from './routes/app/alerts.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsIndexRoute = AppAlertsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAlertsRoute,
} as any)
const AppRulesNewRoute = AppRulesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRulesRoute,
} as any)
const AppRulesIdRoute = AppRulesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRulesRoute,
} as any)
const AppAlertsIdRoute = AppAlertsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAlertsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/alerts': typeof AppAlertsRouteWithChildren
  '/app/documents': typeof AppDocumentsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/rules': typeof AppRulesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/alerts/$id': typeof AppAlertsIdRoute
  '/app/rules/$id': typeof AppRulesIdRoute
  '/app/rules/new': typeof AppRulesNewRoute
  '/app/alerts/': typeof AppAlertsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/rules': typeof AppRulesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/alerts/$id': typeof AppAlertsIdRoute
  '/app/rules/$id': typeof AppRulesIdRoute
  '/app/rules/new': typeof AppRulesNewRoute
  '/app/alerts': typeof AppAlertsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/alerts': typeof AppAlertsRouteWithChildren
  '/app/documents': typeof AppDocumentsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/rules': typeof AppRulesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/alerts/$id': typeof AppAlertsIdRoute
  '/app/rules/$id': typeof AppRulesIdRoute
  '/app/rules/new': typeof AppRulesNewRoute
  '/app/alerts/': typeof AppAlertsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/alerts'
    | '/app/documents'
    | '/app/onboarding'
    | '/app/rules'
    | '/app/settings'
    | '/app/'
    | '/app/alerts/$id'
    | '/app/rules/$id'
    | '/app/rules/new'
    | '/app/alerts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/documents'
    | '/app/onboarding'
    | '/app/rules'
    | '/app/settings'
    | '/app'
    | '/app/alerts/$id'
    | '/app/rules/$id'
    | '/app/rules/new'
    | '/app/alerts'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/alerts'
    | '/app/documents'
    | '/app/onboarding'
    | '/app/rules'
    | '/app/settings'
    | '/app/'
    | '/app/alerts/$id'
    | '/app/rules/$id'
    | '/app/rules/new'
    | '/app/alerts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rules': {
      id: '/app/rules'
      path: '/rules'
      fullPath: '/app/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts/': {
      id: '/app/alerts/'
      path: '/'
      fullPath: '/app/alerts/'
      preLoaderRoute: typeof AppAlertsIndexRouteImport
      parentRoute: typeof AppAlertsRoute
    }
    '/app/rules/new': {
      id: '/app/rules/new'
      path: '/new'
      fullPath: '/app/rules/new'
      preLoaderRoute: typeof AppRulesNewRouteImport
      parentRoute: typeof AppRulesRoute
    }
    '/app/rules/$id': {
      id: '/app/rules/$id'
      path: '/$id'
      fullPath: '/app/rules/$id'
      preLoaderRoute: typeof AppRulesIdRouteImport
      parentRoute: typeof AppRulesRoute
    }
    '/app/alerts/$id': {
      id: '/app/alerts/$id'
      path: '/$id'
      fullPath: '/app/alerts/$id'
      preLoaderRoute: typeof AppAlertsIdRouteImport
      parentRoute: typeof AppAlertsRoute
    }
  }
}

interface AppAlertsRouteChildren {
  AppAlertsIdRoute: typeof AppAlertsIdRoute
  AppAlertsIndexRoute: typeof AppAlertsIndexRoute
}

const AppAlertsRouteChildren: AppAlertsRouteChildren = {
  AppAlertsIdRoute: AppAlertsIdRoute,
  AppAlertsIndexRoute: AppAlertsIndexRoute,
}

const AppAlertsRouteWithChildren = AppAlertsRoute._addFileChildren(
  AppAlertsRouteChildren,
)

interface AppRulesRouteChildren {
  AppRulesIdRoute: typeof AppRulesIdRoute
  AppRulesNewRoute: typeof AppRulesNewRoute
}

const AppRulesRouteChildren: AppRulesRouteChildren = {
  AppRulesIdRoute: AppRulesIdRoute,
  AppRulesNewRoute: AppRulesNewRoute,
}

const AppRulesRouteWithChildren = AppRulesRoute._addFileChildren(
  AppRulesRouteChildren,
)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRouteWithChildren
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppRulesRoute: typeof AppRulesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRouteWithChildren,
  AppDocumentsRoute: AppDocumentsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppRulesRoute: AppRulesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
